create table item (
  id int unsigned primary key auto_increment not null,
  title varchar(255) not null
);

create table burger (
  id int primary key auto_increment not null,
  name VARCHAR(255) NOT NULL,
  img VARCHAR(511),
  price INTEGER NOT NULL,
  description LONGTEXT NOT NULL,
  list_of_ingredients LONGTEXT NOT NULL,
  spicy TINYINT DEFAULT false,
  size VARCHAR(255)
);

INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Classic Cheeseburger','classic_cheeseburger.jpg',9.99,'A timeless favorite with a juicy beef patty, melted cheddar cheese, lettuce, tomato, onions, and pickles.','Beef patty, cheddar cheese, lettuce, tomato, onions, pickles, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Bacon Avocado Burger','bacon_avocado_burger.jpg',11.99,'Deluxe burger with crispy bacon, creamy avocado slices, lettuce, tomato, and mayonnaise.','Beef patty, bacon, avocado, lettuce, tomato, mayonnaise, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Mushroom Swiss Burger','mushroom_swiss_burger.jpg',10.99,'Savory burger topped with sautéed mushrooms, melted Swiss cheese, lettuce, and mayonnaise.','Beef patty, Swiss cheese, mushrooms, lettuce, mayonnaise, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('BBQ Bacon Burger','bbq_bacon_burger.jpg',11.99,'Flavor-packed burger with barbecue sauce, crispy bacon, cheddar cheese, lettuce, and onions.','Beef patty, bacon, cheddar cheese, barbecue sauce, lettuce, onions, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Southwest Chipotle Burger','southwest_chipotle_burger.jpg',12.99,'spicy burger with chipotle mayo, pepper jack cheese, jalapeños, lettuce, and tomato.','Beef patty, pepper jack cheese, chipotle mayo, jalapeños, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('California Turkey Burger','california_turkey_burger.jpg',10.99,'Healthy and delicious burger with a turkey patty, avocado, lettuce, tomato, and sprouts.','Turkey patty, avocado, lettuce, tomato, sprouts, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Veggie Burger','veggie_burger.jpg',9.99,'Vegetarian delight! A flavorful veggie patty with lettuce, tomato, onions, pickles, and vegan mayo.','Veggie patty, lettuce, tomato, onions, pickles, vegan mayo, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Jalapeño Popper Burger','jalapeno_popper_burger.jpg',11.99,'spicy and indulgent burger with jalapeño poppers, cream cheese, lettuce, and chipotle aioli.','Beef patty, cream cheese, jalapeño poppers, lettuce, chipotle aioli, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Teriyaki Pineapple Burger','teriyaki_pineapple_burger.jpg',12.99,'Tropical twist on a burger with teriyaki sauce, grilled pineapple, Swiss cheese, lettuce, and tomato.','Beef patty, Swiss cheese, teriyaki sauce, grilled pineapple, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Buffalo Chicken Burger','buffalo_chicken_burger.jpg',11.99,'Fiery burger featuring buffalo sauce, crispy chicken patty, blue cheese dressing, lettuce, and tomato.','Chicken patty, buffalo sauce, blue cheese dressing, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Guacamole Bacon Burger','guacamole_bacon_burger.jpg',12.99,'Irresistible burger with guacamole, crispy bacon, pepper jack cheese, lettuce, and tomato.','Beef patty, pepper jack cheese, guacamole, bacon, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Blue Cheese Burger','blue_cheese_burger.jpg',10.99,'Bold and tangy burger with creamy blue cheese, caramelized onions, lettuce, and tomato.','Beef patty, blue cheese, caramelized onions, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('BBQ Ranch Chicken Burger','bbq_ranch_chicken_burger.jpg',11.99,'Flavorful chicken burger with barbecue sauce, ranch dressing, lettuce, and crispy onion straws.','Chicken patty, barbecue sauce, ranch dressing, lettuce, onion straws, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Portobello Mushroom Burger','portobello_mushroom_burger.jpg',10.99,'Vegetarian burger featuring a juicy portobello mushroom cap, Swiss cheese, lettuce, and balsamic glaze.','Portobello mushroom cap, Swiss cheese, lettuce, balsamic glaze, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Cajun Turkey Burger','cajun_turkey_burger.jpg',10.99,'spicy and flavorful turkey burger seasoned with Cajun spices, topped with pepper jack cheese, lettuce, and chipotle mayo.','Turkey patty, pepper jack cheese, Cajun spices, lettuce, chipotle mayo, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Caprese Burger','caprese_burger.jpg',11.99,'Fresh and elegant burger with juicy beef patty, mozzarella cheese, tomato, basil pesto, and balsamic glaze.','Beef patty, mozzarella cheese, tomato, basil pesto, balsamic glaze, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Black Bean Burger','black_bean_burger.jpg',9.99,'Vegetarian burger made with hearty black beans, topped with pepper jack cheese, lettuce, tomato, and chipotle aioli.','Black bean patty, pepper jack cheese, lettuce, tomato, chipotle aioli, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Hawaiian Chicken Burger','hawaiian_chicken_burger.jpg',11.99,'Tropical burger with grilled chicken, grilled pineapple, teriyaki sauce, lettuce, and mayo.','Chicken patty, grilled pineapple, teriyaki sauce, lettuce, mayo, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('spicy Sriracha Burger','spicy_sriracha_burger.jpg',11.99,'Fiery burger with spicy sriracha sauce, pepper jack cheese, jalapeños, lettuce, and chipotle aioli.','Beef patty, pepper jack cheese, sriracha sauce, jalapeños, lettuce, chipotle aioli, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Mediterranean Lamb Burger','mediterranean_lamb_burger.jpg',12.99,'Exotic burger with juicy lamb patty, tzatziki sauce, feta cheese, lettuce, and tomato.','Lamb patty, tzatziki sauce, feta cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('The Works Burger','the_works_burger.jpg',13.99,'Loaded burger with all the fixings! Beef patty, bacon, fried egg, onion rings, cheddar cheese, lettuce, and tomato.','Beef patty, bacon, fried egg, onion rings, cheddar cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Gourmet Veggie Burger','gourmet_veggie_burger.jpg',10.99,'Upscale veggie burger with quinoa patty, roasted red pepper, arugula, goat cheese, and balsamic glaze.','Quinoa patty, roasted red pepper, arugula, goat cheese, balsamic glaze, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Philly Cheesesteak Burger','philly_cheesesteak_burger.jpg',12.99,'Burger version of the Philly classic! Beef patty, grilled peppers and onions, provolone cheese, and mayo.','Beef patty, grilled peppers, grilled onions, provolone cheese, mayo, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Thai Peanut Chicken Burger','thai_peanut_chicken_burger.jpg',12.99,'Exotic burger with Thai peanut sauce, grilled chicken, shredded cabbage, cilantro, and lime wedges.','Chicken patty, Thai peanut sauce, shredded cabbage, cilantro, lime wedges, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Honey Mustard Turkey Burger','honey_mustard_turkey_burger.jpg',11.99,'Savory turkey burger with honey mustard sauce, Swiss cheese, lettuce, and tomato.','Turkey patty, honey mustard sauce, Swiss cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Cajun Shrimp Burger','cajun_shrimp_burger.jpg',13.99,'Zesty burger with Cajun seasoned shrimp, remoulade sauce, lettuce, and tomato.','Shrimp patty, Cajun seasoning, remoulade sauce, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Fiesta Black Bean Burger','fiesta_black_bean_burger.jpg',10.99,'spicy black bean burger with salsa, pepper jack cheese, lettuce, and avocado.','Black bean patty, salsa, pepper jack cheese, lettuce, avocado, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Pesto Chicken Burger','pesto_chicken_burger.jpg',12.99,'Fresh and flavorful burger with basil pesto, grilled chicken, sun-dried tomatoes, and arugula.','Chicken patty, basil pesto, sun-dried tomatoes, arugula, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Mediterranean Lamb Burger','mediterranean_lamb_burger.jpg',12.99,'Exotic burger with juicy lamb patty, tzatziki sauce, feta cheese, lettuce, and tomato.','Lamb patty, tzatziki sauce, feta cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Chicken Caesar Burger','chicken_caesar_burger.jpg',11.99,'Classic Caesar salad flavors on a burger! Grilled chicken, romaine lettuce, parmesan cheese, and Caesar dressing.','Grilled chicken, romaine lettuce, parmesan cheese, Caesar dressing, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Jalapeño Guacamole Burger','jalapeno_guacamole_burger.jpg',12.99,'spicy and creamy burger with jalapeño guacamole, pepper jack cheese, lettuce, and tomato.','Beef patty, pepper jack cheese, jalapeño guacamole, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Caprese Chicken Burger','caprese_chicken_burger.jpg',12.99,'Fresh and elegant burger with grilled chicken, mozzarella cheese, tomato, basil pesto, and balsamic glaze.','Grilled chicken, mozzarella cheese, tomato, basil pesto, balsamic glaze, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Turkey Club Burger','turkey_club_burger.jpg',11.99,'Tasty turkey burger with crispy bacon, Swiss cheese, lettuce, tomato, and mayonnaise.','Turkey patty, bacon, Swiss cheese, lettuce, tomato, mayonnaise, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Portobello Swiss Burger','portobello_swiss_burger.jpg',11.99,'Vegetarian burger with grilled portobello mushroom, Swiss cheese, lettuce, and garlic aioli.','Portobello mushroom, Swiss cheese, lettuce, garlic aioli, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Blue Cheese Bacon Burger','blue_cheese_bacon_burger.jpg',12.99,'Bold and flavorful burger with blue cheese crumbles, crispy bacon, lettuce, and tomato.','Beef patty, blue cheese crumbles, bacon, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Pineapple Teriyaki Chicken Burger','pineapple_teriyaki_chicken_burger.jpg',12.99,'Tropical burger with grilled chicken, teriyaki sauce, grilled pineapple, lettuce, and mayo.','Grilled chicken, teriyaki sauce, grilled pineapple, lettuce, mayo, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Chili Cheeseburger','chili_cheeseburger.jpg',11.99,'Hearty burger with beef chili, cheddar cheese, lettuce, and onions.','Beef patty, beef chili, cheddar cheese, lettuce, onions, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Hawaiian Turkey Burger','hawaiian_turkey_burger.jpg',11.99,'Tropical twist on a turkey burger with grilled pineapple, Swiss cheese, lettuce, and teriyaki mayo.','Turkey patty, grilled pineapple, Swiss cheese, lettuce, teriyaki mayo, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Black and Bleu Burger','black_and_bleu_burger.jpg',12.99,'Bold burger with blackened beef patty, tangy blue cheese, lettuce, and tomato.','Blackened beef patty, blue cheese, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Chipotle Turkey Burger','chipotle_turkey_burger.jpg',11.99,'spicy and flavorful turkey burger with chipotle mayo, pepper jack cheese, lettuce, and tomato.','Turkey patty, chipotle mayo, pepper jack cheese, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('BBQ Bacon Ranch Burger','bbq_bacon_ranch_burger.jpg',12.99,'Delicious burger with barbecue sauce, crispy bacon, ranch dressing, lettuce, and tomato.','Beef patty, bacon, barbecue sauce, ranch dressing, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Teriyaki Salmon Burger','teriyaki_salmon_burger.jpg',13.99,'Healthy and flavorful burger with teriyaki glazed salmon, lettuce, tomato, and wasabi mayo.','Salmon patty, teriyaki glaze, lettuce, tomato, wasabi mayo, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Buffalo Blue Chicken Burger','buffalo_blue_chicken_burger.jpg',12.99,'spicy chicken burger with buffalo sauce, blue cheese crumbles, lettuce, and tomato.','Chicken patty, buffalo sauce, blue cheese crumbles, lettuce, tomato, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Sriracha Honey Chicken Burger','sriracha_honey_chicken_burger.jpg',12.99,'Sweet and spicy chicken burger with sriracha honey sauce, lettuce, and pickles.','Chicken patty, sriracha honey sauce, lettuce, pickles, burger bun',1,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Greek Lamb Burger','greek_lamb_burger.jpg',13.99,'Mediterranean-inspired burger with juicy lamb patty, tzatziki sauce, feta cheese, lettuce, and tomato.','Lamb patty, tzatziki sauce, feta cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Balsamic Portobello Burger','balsamic_portobello_burger.jpg',11.99,'Vegetarian burger with balsamic marinated portobello mushroom, Swiss cheese, lettuce, and tomato.','Portobello mushroom, Swiss cheese, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Sweet Potato Veggie Burger','sweet_potato_veggie_burger.jpg',10.99,'Healthy and satisfying veggie burger with a sweet potato patty, avocado, lettuce, and tomato.','Sweet potato patty, avocado, lettuce, tomato, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Feta Turkey Burger','feta_turkey_burger.jpg',11.99,'Flavorful turkey burger with crumbled feta cheese, roasted red peppers, lettuce, and tzatziki sauce.','Turkey patty, feta cheese, roasted red peppers, lettuce, tzatziki sauce, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('BBQ Pulled Pork Burger','bbq_pulled_pork_burger.jpg',12.99,'Hearty burger with tender barbecue pulled pork, coleslaw, cheddar cheese, and pickles.','Barbecue pulled pork, coleslaw, cheddar cheese, pickles, burger bun',0,'medium');
INSERT INTO burger(name,img,price,description,list_of_ingredients,spicy,size) VALUES ('Turkey Cranberry Burger','turkey_cranberry_burger.jpg',11.99,'Festive burger with turkey patty, cranberry sauce, brie cheese, lettuce, and arugula.','Turkey patty, cranberry sauce, brie cheese, lettuce, arugula, burger bun',0,'medium');

